build:
  version: "1.0"

accounts:
  message: "Welcome to  accounts related local APIs "
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "dragos@accounts.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932

