apiVersion: apps/v1
kind: Deployment   #is predefined in Kubernetes as one of the core API resources.
metadata:
  name: configserver-deployment
  labels:
    app: configserver
spec:
  replicas: 1 # Number of instances (pods) for this deployment. For example, if set to 2, there will be 2 instances (pods) running in the worker nodes.
  selector:
    matchLabels:
      app: configserver 
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
      - name: configserver
        image: docker.io/aarafahub/configserver:s12 # Specify the container image and tag to deploy in the Kubernetes cluster.
        ports:
        - containerPort: 8071 # Port exposed inside the container.
---
apiVersion: v1
kind: Service #is predefined in Kubernetes as one of the core API resources.
metadata:
  name: configserver
spec:
  selector:
    app: configserver
  type: LoadBalancer # Exposes the microservice externally through a LoadBalancer on port 8071.
  ports:
    - protocol: TCP
      port: 8071 # External port that clients use to connect to the service.
      targetPort: 8071 # Port inside the container to which traffic is forwarded.
