server:
    port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
  datasource:
    url: jdbc:h2:mem:testdb
    username: 'sa'
    pasword: ''
  h2:
    console:
      enabled:true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate: ddl-auto:update
    show-sql: true

management:
  endpoints:
    web:
      exposure: # here all the endpoints of actuator are exposed for our cards service
        include: "*" # use "refresh" if you need only refresh endpoint
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes: #INFO : Enabling probes ensures the system actively verifies whether the application is operational and ready to serve requests
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "cards"
    description: "Cards Application"
    version: "1.0.0"

logging:
  level:
    com:
      springwithaarafa:
        loans: DEBUG














